### ISSUE TITLE
utils.py:139: RuntimeWarning: divide by zero encountered in log10   pvals = -np.log10(pval_col)

### ISSUE THREAD

**Issue by meyana301** [karmel/homer-idr#8]
I just made all peak calling on replicates, pool and pseudoreps. I am now calling the homer idr using:

`python /home/emilie/homer-idr/homer-idr/idr/run_idr.py idr -p peaks/replicates/* -pr peaks/pseudoreps/* -ppr peaks/pooled-pseudoreps/* --pooled_peaks peaks/pooled/peaks.txt -o IDR`

But I get the following error:

```
/home/emilie/homer-idr/homer-idr/idr/utils.py:139: RuntimeWarning: divide by zero encountered in log10
  pvals = -np.log10(pval_col)
Traceback (most recent call last):
  File "/home/emilie/homer-idr/homer-idr/idr/run_idr.py", line 385, in <module>
    parser.idr(options)
  File "/home/emilie/homer-idr/homer-idr/idr/run_idr.py", line 218, in idr
    output_dir=narrowpeak_dir)
  File "/home/emilie/homer-idr/homer-idr/idr/run_idr.py", line 122, in homer2narrow
    idrutils.homer_to_narrow_peaks(data, output_file)
  File "/home/emilie/homer-idr/homer-idr/idr/utils.py", line 156, in homer_to_narrow_peaks
    df = df.sort(['signalValue', 'pValue'], ascending=False)
  File "/home/emilie/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 5067, in __getattr__
    return object.__getattribute__(self, name)
```

The folder in which I am executing the command is organized as so:

```
peaks
- replicates
--rep1.txt
--rep2.txt
- pooled
--peaks.txt
- pseudoreps
--rep1.1.txt
--rep1.2.txt
--rep2.1.txt
--rep2.2.txt
- pooled-pseudoreps
--rep.1.txt
--rep.2.txt
```

 I hope you'll be able to help me figure this out :) Thanks!

**Comment by CurlsForScience** [comment]
Did you figure out how to resolve this? I am having the same error.

**Comment by CurlsForScience** [comment]
For future reference, this appears to be an error with pandas versions. sort is deprecated. I changed line 156 of utils.py to be 
df = df.sort_values(['signalValue', 'pValue'], ascending=False)
and that seemded to resolve the issue. I am using pandas v1.0.1 with python3.8.0.
